In [128]:
import numpy as np
import pandas as pd

attrition_df = pd.read_csv('hr_attrition_dataset.csv')
attrition_df.head()

,employee_id,age,gender,marital_status,education,education_field,num_companies_worked,department,job_role,job_level,...,performance_rating,training_times_last_year,promotions_last_5years,years_since_last_promotion,skills_growth_opportunities,manager_rating,team_size,distance_from_home_km,remote_work_days_per_week,attrition
0,EMP_00000001,35,Male,Married,Bachelor,Business,1,IT,Junior,4,...,3.0,6,3,1,Low,4,8,24,2,Yes
1,EMP_00000002,44,Male,Divorced,Bachelor,Arts,1,Sales,Junior,2,...,5.0,0,0,0,Low,4,6,13,2,Yes
2,EMP_00000003,38,Female,Single,Bachelor,Business,3,Finance,Senior,5,...,5.0,3,0,2,Medium,4,7,6,0,No
3,EMP_00000004,40,Male,Single,Master,Business,5,Sales,Junior,3,...,4.0,6,0,5,High,4,6,3,1,No
4,EMP_00000005,32,Male,Single,Master,Technical,1,Sales,Junior,3,...,3.0,3,0,5,High,3,5,11,0,No

In [129]:
# attrition_df = attrition_df.drop_duplicates()
attrition_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 35 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   employee_id                  15000 non-null  str
 1   age                          15000 non-null  int64
 2   gender                       15000 non-null  str
 3   marital_status               15000 non-null  str
 4   education                    15000 non-null  str
 5   education_field              15000 non-null  str
 6   num_companies_worked         15000 non-null  int64
 7   department                   15000 non-null  str
 8   job_role                     15000 non-null  str
 9   job_level                    15000 non-null  int64
 10  employment_type              15000 non-null  str
 11  years_at_company             15000 non-null  int64
 12  years_in_current_role        15000 non-null  int64
 13  total_working_years          15000 non-null  int64
 14  monthly_income               14550 non-null  float64
 15  percent_salary_hike          15000 non-null  int64
 16  stock_option_level           15000 non-null  int64
 17  bonus_eligible               15000 non-null  str
 18  overtime_paid_eligible       15000 non-null  str
 19  business_travel              15000 non-null  str
 20  work_life_balance            15000 non-null  int64
 21  job_satisfaction             14550 non-null  float64
 22  environment_satisfaction     15000 non-null  int64
 23  relationship_satisfaction    15000 non-null  int64
 24  overtime_hours_per_week      15000 non-null  int64
 25  performance_rating           14550 non-null  float64
 26  training_times_last_year     15000 non-null  int64
 27  promotions_last_5years       15000 non-null  int64
 28  years_since_last_promotion   15000 non-null  int64
 29  skills_growth_opportunities  15000 non-null  str
 30  manager_rating               15000 non-null  int64
 31  team_size                    15000 non-null  int64
 32  distance_from_home_km        15000 non-null  int64
 33  remote_work_days_per_week    15000 non-null  int64
 34  attrition                    15000 non-null  str
dtypes: float64(3), int64(19), str(13)
memory usage: 4.0 MB

In [130]:
res = attrition_df.isnull().sum()
display(res)

employee_id                      0
age                              0
gender                           0
marital_status                   0
education                        0
education_field                  0
num_companies_worked             0
department                       0
job_role                         0
job_level                        0
employment_type                  0
years_at_company                 0
years_in_current_role            0
total_working_years              0
monthly_income                 450
percent_salary_hike              0
stock_option_level               0
bonus_eligible                   0
overtime_paid_eligible           0
business_travel                  0
work_life_balance                0
job_satisfaction               450
environment_satisfaction         0
relationship_satisfaction        0
overtime_hours_per_week          0
performance_rating             450
training_times_last_year         0
promotions_last_5years           0
years_since_last_promotion       0
skills_growth_opportunities      0
manager_rating                   0
team_size                        0
distance_from_home_km            0
remote_work_days_per_week        0
attrition                        0
dtype: int64

In [131]:
attrition_df = attrition_df[
    (attrition_df['department']=='Finance') & 
    (attrition_df['job_role']=='Analyst') & 
    (attrition_df['job_level']==4) &
    (attrition_df['employment_type']=='Full-time')
]
attrition_df = attrition_df[['employee_id','years_at_company','years_in_current_role','total_working_years','monthly_income', 'attrition']].sort_values(
    ['years_at_company', 'years_in_current_role', 'total_working_years','monthly_income'], ascending=False
)
display(attrition_df)

,employee_id,years_at_company,years_in_current_role,total_working_years,monthly_income,attrition
10814,EMP_00010815,10,1,11,1806.0,Yes
1326,EMP_00001327,10,0,11,3005.0,No
13835,EMP_00013836,10,0,10,2258.0,No
7812,EMP_00007813,5,5,5,7807.0,No
6629,EMP_00006630,5,3,7,5548.0,No
9108,EMP_00009109,5,3,6,4110.0,No
577,EMP_00000578,4,0,7,2931.0,No
4044,EMP_00004045,3,13,5,5716.0,No
5221,EMP_00005222,3,1,6,2329.0,No
3215,EMP_00003216,2,1,4,3393.0,No
2553,EMP_00002554,2,0,8,7729.0,Yes
10119,EMP_00010120,1,4,9,2625.0,No
11655,EMP_00011656,1,3,2,1621.0,Yes
1793,EMP_00001794,1,2,10,8760.0,Yes
13048,EMP_00013049,0,7,4,1670.0,No
5083,EMP_00005084,0,3,5,4556.0,Yes
6819,EMP_00006820,0,1,0,3229.0,Yes
7463,EMP_00007464,0,0,7,3215.0,No
8321,EMP_00008322,0,0,1,3536.0,No

In [132]:
attrition_df = attrition_df.fillna({
    'monthly_income': attrition_df.groupby(['department', 'job_role'])['monthly_income'].transform('mean')
})
attrition_df = attrition_df[['employee_id', 'department', 'job_role', 'monthly_income', 'attrition']]
display(attrition_df)

KeyError: 'department'