In [35]:
import numpy as np
import pandas as pd

df = pd.read_csv('5_hr_attrition.csv')
df.head()

,employee_id,age,gender,marital_status,education,education_field,num_companies_worked,department,job_role,job_level,...,performance_rating,training_times_last_year,promotions_last_5years,years_since_last_promotion,skills_growth_opportunities,manager_rating,team_size,distance_from_home_km,remote_work_days_per_week,attrition
0,EMP_00000001,35,Male,Married,Bachelor,Business,1,IT,Junior,4,...,3.0,6,3,1,Low,4,8,24,2,Yes
1,EMP_00000002,44,Male,Divorced,Bachelor,Arts,1,Sales,Junior,2,...,5.0,0,0,0,Low,4,6,13,2,Yes
2,EMP_00000003,38,Female,Single,Bachelor,Business,3,Finance,Senior,5,...,5.0,3,0,2,Medium,4,7,6,0,No
3,EMP_00000004,40,Male,Single,Master,Business,5,Sales,Junior,3,...,4.0,6,0,5,High,4,6,3,1,No
4,EMP_00000005,32,Male,Single,Master,Technical,1,Sales,Junior,3,...,3.0,3,0,5,High,3,5,11,0,No

In [36]:
print(df.columns)

Index(['employee_id', 'age', 'gender', 'marital_status', 'education',
       'education_field', 'num_companies_worked', 'department', 'job_role',
       'job_level', 'employment_type', 'years_at_company',
       'years_in_current_role', 'total_working_years', 'monthly_income',
       'percent_salary_hike', 'stock_option_level', 'bonus_eligible',
       'overtime_paid_eligible', 'business_travel', 'work_life_balance',
       'job_satisfaction', 'environment_satisfaction',
       'relationship_satisfaction', 'overtime_hours_per_week',
       'performance_rating', 'training_times_last_year',
       'promotions_last_5years', 'years_since_last_promotion',
       'skills_growth_opportunities', 'manager_rating', 'team_size',
       'distance_from_home_km', 'remote_work_days_per_week', 'attrition'],
      dtype='str')

In [37]:
attrition_df = df[df['attrition']=='Yes']
display(attrition_df)

,employee_id,age,gender,marital_status,education,education_field,num_companies_worked,department,job_role,job_level,...,performance_rating,training_times_last_year,promotions_last_5years,years_since_last_promotion,skills_growth_opportunities,manager_rating,team_size,distance_from_home_km,remote_work_days_per_week,attrition
0,EMP_00000001,35,Male,Married,Bachelor,Business,1,IT,Junior,4,...,3.0,6,3,1,Low,4,8,24,2,Yes
1,EMP_00000002,44,Male,Divorced,Bachelor,Arts,1,Sales,Junior,2,...,5.0,0,0,0,Low,4,6,13,2,Yes
7,EMP_00000008,52,Female,Divorced,High School,Business,2,Sales,Analyst,4,...,4.0,3,0,1,Low,4,7,20,0,Yes
8,EMP_00000009,23,Male,Married,PhD,Business,1,Operations,Junior,2,...,5.0,3,1,0,Low,4,5,26,3,Yes
13,EMP_00000014,51,Other,Single,Master,Business,2,IT,Junior,1,...,4.0,6,0,5,High,3,7,18,2,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14988,EMP_00014989,22,Male,Single,Master,Science,2,R&D,Manager,2,...,3.0,7,1,6,High,3,5,14,5,Yes
14994,EMP_00014995,22,Female,Single,Master,Science,1,IT,Junior,2,...,4.0,2,0,5,Low,3,8,24,1,Yes
14995,EMP_00014996,48,Male,Single,High School,Business,1,Sales,Junior,2,...,3.0,2,0,2,Medium,4,13,3,2,Yes
14996,EMP_00014997,29,Female,Married,High School,Business,7,Operations,Junior,5,...,4.0,3,0,4,Low,5,4,1,0,Yes
14999,EMP_00015000,39,Female,Married,PhD,Science,2,IT,Junior,1,...,3.0,4,0,6,Medium,4,3,18,0,Yes

In [38]:
attrition_df = attrition_df[(attrition_df['attrition']=='Yes')]
attrition_df = attrition_df.groupby(['martialstatus']).agg({
    'attrition_count': ('attrition', 'count')
})
display(attrition_df)

KeyError: 'martialstatus'